# Kebernetes service yaml
# that have main 4 elements
#   01. apiVersion
#   02. kind
#   03. metadata
#   04. spec

apiVersion: v1
kind: Service
metadata:
  name: sample-app-1
spec:
  selector:
    app: myapp
  ports:
    - port: 8989
      targetPort: <Target Port>
